class Constants:

	UNIQUE_KEY = 'ic_'
	DATABASE_ERROR = 500
	INVALID_INPUT = 400
	SUCCESS_CODE = 200
	INVALID_EMAIL = 'Invalid email id'
	STATUS_FAILED = 'Failed'
	STATUS_SUCCESS = 'Success'
	INVALID_JSON = 'Invalid JSON'
	BASE_ID_COOK = 100000
	INTEGRITY_ERROR = "User already exists"
	INTEGRITY_ERROR_CODE = 'ic_500'
	NO_USER_FOUND = 'ic_404'
	USER_NOT_REGISTER = 'Not a registered user'
	INVALID_PASSWORD_CODE = 401
	INVALID_PASSWORD = 'Invalid password'
